### ISSUE TITLE
Content Prep - Run link checker to confirm URL Redirects

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/d9-emory-libraries#211]
Hour of Launch:

**Comment by rotated8** [comment]
[Results](https://emory-my.sharepoint.com/:x:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Web%20Redesign%20Project/Acquia%20CMS%20Migration%202021/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/checked_links_oxford.csv?d=w1a129b71e66d4e5e861bde0d9ea6abc1&csf=1&web=1&e=ISwlDz)

**Comment by rosy1280** [comment]
@rotated8 it turns out that .html wasn't at the end of some of the old URLs.  Can you run this again?

**Comment by rotated8** [comment]
[Updated results](https://emory-my.sharepoint.com/:x:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Web%20Redesign%20Project/Acquia%20CMS%20Migration%202021/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/checked_links_oxford.csv?d=w1a129b71e66d4e5e861bde0d9ea6abc1&csf=1&web=1&e=g98pjF)

Six failures, but the first is expected. Rows 3, 4, and 5 have fragments at the end of the URL which may be causing issues?

**Comment by rotated8** [comment]
[Updated results](https://emory-my.sharepoint.com/:x:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Web%20Redesign%20Project/Acquia%20CMS%20Migration%202021/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/checked_links_oxford.csv?d=w1a129b71e66d4e5e861bde0d9ea6abc1&csf=1&web=1&e=g98pjF)

@rosy1280 Six failures, but the first is expected. Rows 3, 4, and 5 have fragments at the end of the URL which may be causing issues? Tried rows 2 and 6 with and without `.html` on the end, both fail.

**Comment by rosy1280** [comment]
thanks @rotated8 .  one of the encoded URLs has a space and drupal doesn't seem to want to handle that (can't say i blame it).  the rest i was able to manually update and fix.  closing this ticket.
